#!/bin/tcsh -f
#
# You may copy this file for other functions
#
cat is_palindrome_driver.s is_palindrome.s > is_palindrome_prog.s
spim -file is_palindrome_prog.s | tail -n +2
rm -f is_palindrome_prog.s

cat reverse_prefix_sum_driver.s reverse_prefix_sum.s > reverse_prefix_sum_prog.s
spim -file reverse_prefix_sum_prog.s | tail -n +2
rm -f reverse_prefix_sum_prog.s

cat collatz_driver.s collatz.s > collatz_prog.s
cat collatz_prog.s collatz_data01.s > collatz_prog_with_data.s
spim -file collatz_prog_with_data.s | tail -n +2
rm -f collatz_prog_with_data.s collatz_prog.s

cat collatz_driver.s collatz.s > collatz_prog.s
cat collatz_prog.s collatz_data02.s > collatz_prog_with_data2.s
spim -file collatz_prog_with_data2.s | tail -n +2
rm -f collatz_prog_with_data2.s collatz_prog.s


cat isqrt_driver.s isqrt.s > isqrt_prog.s
spim -file isqrt_prog.s | tail -n +2
rm -f isqrt_prog.s

# "tail -n+2" strips the first line of spim's output, which is irrelevant